version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./app/dockerfile
      cache_from:
        - study_task-app:latest
    container_name: study_task_app
    ports:
      - "9090:9090"
    environment:
      - api_version=VERSION
    volumes:
      - ./app:/app