FROM python:3.12-slim

WORKDIR /app

COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Копируем содержимое папки app (на хосте) в /app (в контейнере)
COPY app/ . 

CMD ["python3", "main.py"]